version: '3'
services:
  opensearch-cl1-node1:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl1-node1
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    environment:
      - cluster.name=cluster1
      - node.name=opensearch-cl1-node1
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-eng-week4-cl1-n1:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl1-node2:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl1-node2
    environment:
      - cluster.name=cluster1
      - node.name=opensearch-cl1-node2
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-eng-week4-cl1-n2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl1-node3:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl1-node3
    environment:
      - cluster.name=cluster1
      - node.name=opensearch-cl1-node3
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-eng-week4-cl1-n3:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl2-node1:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl2-node1
    ports:
      - 9201:9200
      - 9700:9600 # required for Performance Analyzer
    environment:
      - cluster.name=cluster2
      - node.name=opensearch-cl2-node1
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-eng-week4-cl2-n1:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl2-node2:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl2-node2
    environment:
      - cluster.name=cluster2
      - node.name=opensearch-cl2-node2
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-eng-week4-cl2-n2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-cl2-node3:
    image: opensearchproject/opensearch:2.6.0
    container_name: opensearch-cl2-node3
    environment:
      - cluster.name=cluster2
      - node.name=opensearch-cl2-node3
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - search-eng-week4-cl2-n3:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.6.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-cl1-node1:9200","https://opensearch-cl1-node2:9200","https://opensearch-cl1-node3:9200","https://opensearch-cl2-node1:9200","https://opensearch-cl2-node2:9200","https://opensearch-cl2-node3:9200"]'
    networks:
      - opensearch-net

volumes:
  search-eng-week4-cl1-n1:
  search-eng-week4-cl1-n2:
  search-eng-week4-cl1-n3:
  search-eng-week4-cl2-n1:
  search-eng-week4-cl2-n2:
  search-eng-week4-cl2-n3:

networks:
  opensearch-net:
    name: opensearch-net

